"""update r/ships

Revision ID: 555d0556e0ff
Revises: d86c067fe2de
Create Date: 2025-06-17 07:59:55.531248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555d0556e0ff'
down_revision: Union[str, None] = 'd86c067fe2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'admin', ['admin_id'], ['id'])
    op.add_column('stk_push', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stk_push', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stk_push', type_='foreignkey')
    op.drop_column('stk_push', 'event_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'admin_id')
    # ### end Alembic commands ###
